quiet: False
keeptree: False
disable-version-string: True
with-expecter: False
mockname: '{{.InterfaceName}}'
filename: '{{.MockName}}.go'
dir: '{{.InterfaceDir}}/mocks/'
outpkg: mocks
packages:
  github.com/rubemlrm/go-shelly/shelly/gen1:
    config:
      all: True
  github.com/rubemlrm/go-shelly/shelly/gen1/devices:
    config:
      all: True
  github.com/rubemlrm/go-shelly/shelly/gen1/transport:
    config:
      all: True
  github.com/rubemlrm/go-shelly/shelly/gen1/contracts:
    config:
      all: True
